### ISSUE TITLE
Admin helper tries to add assets from full path

### ISSUE THREAD

**Issue by Rozkalns** [raffaelj/cockpit_ModuleLink#1]
```
<?php

$app->on('admin.init', function() use($app){

    $this->helper('admin')->addAssets(__DIR__.'/assets/component.js');
    $this->helper('admin')->addAssets(__DIR__.'/assets/components/field-module-link.tag');

    $this->bindClass('ModuleLink\\Controller\\Admin', 'modulelink');

});
```
On docker this causes couple of issues of not correctly resolved paths.

![screenshot 2018-10-08 at 15 36 06](https://user-images.githubusercontent.com/8157701/46609432-8b319d80-cb10-11e8-8014-721e151c8cbb.png)

Replacing `__DIR__.'/assets` with `'modulelink:assets` solves the issue.

Maybe there is better way how to fix it.

**Comment by raffaelj** [comment]
I don't have a dockerized environment at hand, so I can't test it. `modulelink:assets` doesn't work if the addon is named `cockpit_ModuleLink`. That't why I used `__DIR__` to prevent auto-registering wrong paths.

I'll change it - and I have to find out the right way to define paths under all possible conditions.

Do you use the Groups Addon, too? If yes, does it throw errors?
There was a related issue: https://github.com/serjoscha87/cockpit_GROUPS/issues/4
