### ISSUE TITLE
Some icons have an incorrect asset path

### ISSUE THREAD

**Issue by jasonday** [raffaelj/cockpit_ModuleLink#2]
This particular icon:
![image](https://user-images.githubusercontent.com/748011/72744844-58cc7800-3b7c-11ea-8dab-5c37e2dddae6.png)

Is broken in ModuleLink
![image](https://user-images.githubusercontent.com/748011/72744948-96c99c00-3b7c-11ea-8cd1-8d234e46ce0c.png)

The images that are showing are SVGs, but for some reason this icon is not an SVG.

The broken path is:
/cockpit/modules/collections/icon.svg

The actual path is:
/cockpit/modules/Collections/icon.svg

Besides that, it appears that Cockpit sometimes using inline SVGs and other times references the SVG through an image tag, but I can't discern why the difference as there doesn't appear to be an organizing principle behind it.

**Comment by raffaelj** [comment]
The icon path should be fixed now.

The image tag confusion has two reasons:

1. With UIKit, you can transform an svg file as img src to inline svg.
https://getuikit.com/v2/docs/utility.html#inline-svg

2. Some images are loaded via `App.assets.require()`. It checks, if the file exists with an invisible image tag in a promise. This is, why an img tag may appear in your browser network console.
https://github.com/agentejo/cockpit/blob/next/assets/app/js/app.js#L249-L260
